# Generated by Django 3.1.2 on 2020-11-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_delete_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correctness_score',
            new_name='age',
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_views',
            field=models.FloatField(default=0),
        ),
    ]
