# Generated by Django 3.1.2 on 2020-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_question_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
